# Generated by Django 3.1.1 on 2020-09-22 23:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_userworks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWorks',
            new_name='UserWorkModel',
        ),
    ]
