# Generated by Django 3.1.1 on 2020-09-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200925_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkmodel',
            name='like_value',
        ),
    ]
