# Generated by Django 3.1.1 on 2020-09-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200928_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkmodel',
            name='photo_name',
        ),
    ]
