# Generated by Django 3.1.1 on 2020-09-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200923_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='account.userworkmodel'),
        ),
    ]
