# Generated by Django 3.1.1 on 2020-09-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200923_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkmodel',
            name='like_value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
